# Generated by Django 4.0.3 on 2022-06-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0006_songinfo_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='song',
            field=models.FileField(upload_to='musican/songs'),
        ),
    ]
