# Generated by Django 4.1.3 on 2022-12-05 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='musican.genre'),
        ),
    ]
