# Generated by Django 4.0.3 on 2022-06-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
