# Generated by Django 4.0.3 on 2022-06-22 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0002_alter_artist_bio_alter_artist_links_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist_name',
        ),
    ]
