# Generated by Django 4.1.3 on 2022-12-11 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0003_playlist_remove_watchlist_item_watched_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.AddField(
            model_name='artist',
            name='is_liked',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='liked_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='num_likes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='is_liked',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='liked_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='num_likes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='songlike',
            name='song_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='musican.songinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='songlike',
            unique_together={('liked_by', 'song_liked')},
        ),
    ]
