# Generated by Django 4.0.3 on 2022-06-22 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0004_alter_artist_artist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albuminfo',
            old_name='name',
            new_name='album_name',
        ),
    ]
