# Generated by Django 4.0.3 on 2022-06-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0005_rename_name_albuminfo_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinfo',
            name='song',
            field=models.FileField(default='test', upload_to=''),
            preserve_default=False,
        ),
    ]
