# Generated by Django 4.0.3 on 2022-06-27 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0007_alter_songinfo_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='song',
            field=models.FileField(upload_to='songs'),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(max_length=30)),
                ('playlist_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_song', to='musican.songinfo')),
                ('playlist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
