# Generated by Django 4.0.3 on 2022-06-27 21:59

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0008_alter_songinfo_song_playlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albuminfo',
            options={'ordering': ['-posted_on']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['-posted_on']},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-posted_on']},
        ),
        migrations.AlterModelOptions(
            name='songinfo',
            options={'ordering': ['-posted_on']},
        ),
        migrations.AddField(
            model_name='albuminfo',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songinfo',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 27, 21, 59, 52, 721760, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
