# Generated by Django 4.0.3 on 2022-06-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0009_alter_albuminfo_options_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_song',
            field=models.ManyToManyField(to='musican.songinfo'),
        ),
    ]
