# Generated by Django 4.0.3 on 2022-06-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0010_remove_playlist_playlist_song_playlist_playlist_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songinfo',
            name='album',
        ),
        migrations.AddField(
            model_name='albuminfo',
            name='songs',
            field=models.ManyToManyField(to='musican.songinfo'),
        ),
    ]
