# Generated by Django 4.0.3 on 2022-06-30 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musican', '0011_remove_songinfo_album_albuminfo_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='albuminfo',
            name='featured_album',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='albuminfo',
            name='played_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='featured_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='featured_playlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='played_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songinfo',
            name='featured_song',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='played_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
