# Generated by Django 4.0.3 on 2022-05-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_posts_currentuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='currentuser',
        ),
    ]
