# Generated by Django 4.0.3 on 2022-04-11 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_posts_liked_by_posts_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='liked_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
