# Generated by Django 4.0.3 on 2022-05-30 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_posts_currentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
