# Generated by Django 4.0.3 on 2022-04-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_posts_sender_alter_posts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='sender',
            new_name='poster',
        ),
    ]
