# Generated by Django 4.0.3 on 2022-04-26 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_posts_user_posts_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
